### ISSUE TITLE
Custom GEOIP-ASN is not working with logstash.

### ISSUE THREAD

**Issue by yasvanth** [maxmind/getting-started-with-mmdb#11]
Hi Team,

I have followed the blog to create a "Geoip-ASN" database and tried to used with logstash geoip filter but no luck.

I could get  the  values from DB using read-script as provided in the repo. The code to generate ASN is given below.

<pre>
#!/usr/bin/env perl

use strict;
use warnings;
use YAML::XS 'LoadFile';
use Data::Dumper;
use feature qw( say );
use local::lib 'local';
use Net::Works::Network;
use MaxMind::DB::Writer::Tree;

# Your top level data structure will always be a map (hash).  The MMDB format
# is strongly typed.  Describe your data types here.
# See https://metacpan.org/pod/MaxMind::DB::Writer::Tree#DATA-TYPES

my %types = (
    autonomous_system_number         => 'uint32',
    autonomous_system_organization   => 'utf8_string',
);

my $tree = MaxMind::DB::Writer::Tree->new(

    # "database_type" is some arbitrary string describing the database.  At
    # MaxMind we use strings like 'GeoIP2-City', 'GeoIP2-Country', etc.
    database_type => 'Geo-ASN',

    # "description" is a hashref where the keys are language names and the
    # values are descriptions of the database in that language.
    description =>
        { en => 'ASN Database', },

    # "ip_version" can be either 4 or 6
    ip_version => 4,

    # add a callback to validate data going in to the database
    map_key_type_callback => sub { $types{ $_[0] } },

    # "record_size" is the record size in bits.  Either 24, 28 or 32.
    record_size => 24,
);
my $config = LoadFile('../files/Network_asn.yml');

# Perl hash to store YAML content
my %address_of_network;

my $file_name = 'TestASN.mmdb';
# Output file for mmdb creation

my $output_file = '../files/' . $file_name;

for (keys %{$config}){
  my @org_network; #network might be an array
  my $org_asn;
  my $org_name;
  my $org_network;

  $org_name = $_;
    #say "Org Name $org_name\n";
    for (keys %{$config->{$org_name}}) {
      $org_asn = $config->{$org_name}->{asn};
      if ( exists ($config->{$org_name}->{network})){
        @org_network = @{$config->{$org_name}->{network}};
        #say " The Network : @org_network\n";
      }
    }
    if (@org_network){
      for (@org_network){
        $org_network = $_;
        #print "$org_name\'s asn is \"$org_asn\" and has following networks: $org_network";
        %address_of_network = (
            $org_network => {
               autonomous_system_number => $org_asn,
               autonomous_system_organization => $org_name,
            }
        );
        for my $address ( keys %address_of_network ) {
             my $network = Net::Works::Network->new_from_string( string => $address );
             $tree->insert_network( $network, $address_of_network{$address} );
          }
      }
    }
}

# Write the database to disk.
open my $fh, '>:raw', $output_file;
$tree->write_tree( $fh );
close $fh;

say "$file_name has now been created"
</pre>

The YAML file consist : 
<pre>
---
team1:
  asn: 0011
  network: 
      - 10.10.1.1
      - 10.10.2.1
team2:
   asn: 0012
   network:
       - 20.20.1.1
</pre>

If you require any further information please do let me know.

Best,
Yash

**Comment by oschwald** [comment]
What error are you getting from Logstash? I might suggest setting the `database_type` to `GeoLite2-ASN` to match the official ASN database.

**Comment by yasvanth** [comment]
Hi @oschwald,
Thanks for your prompt response, changing the database type fixed.

Best,
Yash
