### ISSUE TITLE
Vagrant up getting stuck at user input

### ISSUE THREAD

**Issue by oguzhanunlu** [maxmind/getting-started-with-mmdb#15]
Hi,

I have an issue with interactive vagrant setup and wanted to share how I solved it.

OS: macOS Catalina

Running `vagrant up` gets stuck due to waiting user input

```bash
default: Package configuration┌──────────────────────┤ Configuring libssl1.1:amd64
 ├──────────────────────┐│││ There are services installed on your system which need to be restarted
    ││ when certain libraries, such as libpam, libc, and libssl, are upgraded.   ││ Since these restarts may cause interruptions of 
service for the system,   ││ you will normally be prompted on each upgrade for the list of services    ││ you wish to restart.  You
 can choose this option to avoid being││ prompted; instead, all necessary restarts will be done for you││ automatically so you
 can avoid being asked questions on each library││ upgrade.││││ Restart services during package upgrades without asking?
││││<Yes<No>│││└───────────────────────────────────────────────────────────────────────────┘l.deb ...
```

I wasn't able to select `Yes` or `No` at this point.

After inserting the following to Vagrantfile at line 70, `vagrant up` doesn't wait on user input and finishes successfully.

```bash
echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
```

I guess it isn't the best fix but it worked for me. I can open a PR for this update if maintainers want.

Thanks for the repository and scripts, it helped me prepare tiny test databases!

**Comment by oalders** [comment]
Thanks for this @oguzhanunlu! I'm glad you found this repository helpful. 😄  I've just tried to `vagrant up` and I'm seeing various issues I think we need to fix. I'll poke around a bit.

Having said that, we do now have some faster tooling for building `mmdb` databases. You may be interested in this blog post: https://blog.maxmind.com/2020/09/01/enriching-mmdb-files-with-your-own-data-using-go/

**Comment by oguzhanunlu** [comment]
Thanks @oalders for the quick reply!

I've tried a fresh deployment and it doesn't finish successfully due to `geoipupdate` expecting valid UserId and LicenseKey. After commenting out L93 in Vagrantfile, it still doesn't finish fine, but I can ssh into vm and generate databases.

I'll check the new tooling out! Thanks for sharing!
