### ISSUE TITLE
Can't locate MaxMind/DB/Writer/Tree.pm

### ISSUE THREAD

**Issue by micheljung** [maxmind/getting-started-with-mmdb#3]
Hi,

I installed the latest Vagrant 2.0.0, cloned this repository and followed the instructions:

    vagrant up
    vagrant ssh
    cd /vagrant
    perl examples/01-getting-started.pl

However, I get the following error:

    Can't locate MaxMind/DB/Writer/Tree.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at examples/01-getting-started.pl line 7.
    BEGIN failed--compilation aborted at examples/01-getting-started.pl line 7.

I'm on Windows 10 and since it's all in Vagrant, idk. what other information would be helpful.

**Comment by oalders** [comment]
@micheljung are logged in to your vagrant box via ssh when you run the perl script?

**Comment by oalders** [comment]
ie, this script needs to be run from inside the vagrant VM (the guest) rather than on the host.

**Comment by micheljung** [comment]
Yes, see the commands in the description above. Here's the full output:

```
$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Wed Sep 13 13:48:33 2017 from 10.0.2.2
vagrant@precise64:~$ cd /vagrant
vagrant@precise64:/vagrant$ perl examples/01-getting-started.pl
Can't locate MaxMind/DB/Writer/Tree.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2
 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at examples/01-getting-star
ted.pl line 7.
BEGIN failed--compilation aborted at examples/01-getting-started.pl line 7.
vagrant@precise64:/vagrant$

```

**Comment by oalders** [comment]
@micheljung this should now be fixed if you pull in the latest changes and run another `vagrant provision`.  Let me know if this works?

**Comment by micheljung** [comment]
@oalders oops sorry, yes it works, awesome thanks :)

**Comment by oalders** [comment]
@micheljung thanks for confirming.  :)

**Comment by sbaker87** [comment]
@oalders I have been following the directions, for both the manual install and vagrant options. They both are failing, and I also get the same error when using vagrant:

>  Can't` locate MaxMind/DB/Writer/Tree.pm in @INC (@INC contains: /vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi /vagrant/local/lib/perl5 /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at examples/01-getting-started.pl line 8.
> BEGIN failed--compilation aborted at examples/01-getting-started.pl line

**Comment by oalders** [comment]
@sbaker87 sorry for the delay.  I lost track of this.  Could you see if https://github.com/maxmind/getting-started-with-mmdb/pull/5/files solves it for you?

**Comment by sbaker87** [comment]
This worked for me, thanks!
