### ISSUE TITLE
Iterate_search_tree goes past node count?

### ISSUE THREAD

**Issue by tuangeek** [maxmind/getting-started-with-mmdb#7]
I come from a Python background. This is my first attempt at coding in perl. But I modified the 03-iterate-search-tree.pl example to iterate the database. My goal was trying to time how long it would take to iterate through the database. I've attached my modified script.

```
#!/usr/bin/env perl

use strict;
use warnings;
use feature qw( say );
use local::lib 'local';

use Data::Printer;
use MaxMind::DB::Reader;
use Net::Works::Address;

my $filename = shift @ARGV or die 'Usage: perl traverse.pl [database_file]';

my $reader = MaxMind::DB::Reader->new( file => $filename );
say $reader->metadata()->metadata_to_encode()->{node_count};
my $count = 0;

$reader->iterate_search_tree(
    sub {
        my $ip_as_integer = shift;
        my $mask_length   = shift;
        my $data          = shift;

        my $address = Net::Works::Address->new_from_integer(
            integer => $ip_as_integer );
        # say join '/', $address->as_ipv4_string, $mask_length;
        # say np $data;
        if(($count % 100000) == 0)
        {
            say $count;
        }
        $count++;
    }
);
```

My command to run the script.
```
tuan$time perl traverse.pl GeoLite2-ASN.mmdb
692220
0
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
```

According to this, the database has 692220 nodes. But my count is well over 1 million, and legend has it that the script is still running.

Did I messed up on my script?

**Comment by oalders** [comment]
Hi @tuangeek,

I just checked with my colleagues and the answer I got was that you are probably running into aliased nodes.  Basically the IPv4 space shows up in multiple places.  You might be better off using the ASN CSV as your input data rather than the `mmdb`.

**Comment by tuangeek** [comment]
Awesome. Thanks for the pointer.
