### ISSUE TITLE
Getting weird network masking in results

### ISSUE THREAD

**Issue by tuangeek** [maxmind/getting-started-with-mmdb#8]
I am getting weird results from running 03-iterate-serach-tree.pl especially from line 22. https://github.com/maxmind/getting-started-with-mmdb/blob/57566b3adfd7e89a6510bf743be1577fcbf3a5dc/examples/03-iterate-search-tree.pl#L22

I know of two format that use similar notation, Classless Inter Domain Routing (CIDR) and Variable Length Subnet Mask (VLSM). However the numbers after the `/` is usually less than 32. However in this case it goes up to 120.
Some more results from the latest GeoLite2-City.mmdb :
```
1.0.0.0/120
1.0.1.0/120
1.0.2.0/119
1.0.4.0/118
1.0.8.0/117
1.0.16.0/116
1.0.32.0/115
1.0.64.0/114
1.0.128.0/113
1.1.0.0/120
1.1.1.0/120
1.1.2.0/119
1.1.4.0/118
1.1.8.0/117
1.1.16.0/116
1.1.32.0/115
1.1.64.0/114
1.1.128.0/113
1.2.0.0/119
1.2.2.0/120
```

My networking background is very limited so I can't argue if this format is right or wrong, But according more credible people, network masking can on be /0 to /32. https://networkengineering.stackexchange.com/questions/51636/what-format-is-1-34-128-0-113/51639#51639

**Comment by oschwald** [comment]
This is because you are using `->as_ipv4_string` with the original mask length. The actual IP address in the database is something like `::1.0.0.0`, i.e., an IPv6 address. If you want to get the IPv4 mask length for these, you will need to subtract 96.

**Comment by tuangeek** [comment]
Oh okay. Is there anyway to tell if the database contain ipv4 or ipv6 address?

**Comment by oschwald** [comment]
You can check the `ip_version` in the [metdata](https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md#ip_version). However, if you just used `->as_string` rather than `->as_ipv4_string`, it would be obvious in this case.
